import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

// Setup __dirname untuk ES Module (.mjs)
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

// Konfigurasi Path
const THEMES_DIR = path.join(__dirname, 'src/themes');
const REGISTRY_FILE = path.join(__dirname, 'src/themes/registry.ts');

console.log('🔄 Syncing Themes...');

try {
    // 1. Baca isi folder src/themes
    if (!fs.existsSync(THEMES_DIR)) {
        console.error(`❌ Folder themes tidak ditemukan di: ${THEMES_DIR}`);
        process.exit(1);
    }

    const items = fs.readdirSync(THEMES_DIR);

    // 2. Filter folder yang valid (punya theme.json & index.ts)
    const validThemes = items.filter(item => {
        const itemPath = path.join(THEMES_DIR, item);
        return fs.statSync(itemPath).isDirectory() && 
               fs.existsSync(path.join(itemPath, 'theme.json')) &&
               fs.existsSync(path.join(itemPath, 'index.ts'));
    });

    console.log(`📂 Ditemukan ${validThemes.length} tema: ${validThemes.join(', ')}`);

    // 3. Generate konten registry.ts
    let importStatements = '';
    let exportMap = '';

    validThemes.forEach(theme => {
        // Ubah nama folder jadi variabel aman (misal: labmu-news -> labmu_news)
        const varName = theme.replace(/[^a-zA-Z0-9]/g, '_');
        
        importStatements += `import * as ${varName} from './${theme}';\n`;
        exportMap += `    '${theme}': ${varName},\n`;
    });

    const fileContent = `// ⚠️ GENERATED BY sync-themes.mjs
// Do not edit manually. Run 'npm run sync-themes' to update.

${importStatements}

export const themes: Record<string, any> = {
${exportMap}};

export const getThemeList = () => {
    return Object.keys(themes).map(key => {
        const t = themes[key];
        // Fallback jika meta tidak di-export, baca minimal data
        return t.meta || { 
            id: key, 
            name: key, 
            version: '0.0.0', 
            author: 'Unknown', 
            description: 'No description' 
        };
    });
};
`;

    // 4. Tulis file
    fs.writeFileSync(REGISTRY_FILE, fileContent);
    console.log(`✅ Sukses update: src/themes/registry.ts`);

} catch (err) {
    console.error('❌ Gagal sync themes:', err);
    process.exit(1);
}