// src/themes/labmu-quran/list-surat.ts

export const ListSurat = [
  { nomor: 1, nama: "الفاتحة", namaLatin: "Al-Fatihah", slug: "al-fatihah", jumlahAyat: 7, tempatTurun: "Mekah", arti: "Pembukaan" },
  { nomor: 2, nama: "البقرة", namaLatin: "Al-Baqarah", slug: "al-baqarah", jumlahAyat: 286, tempatTurun: "Madinah", arti: "Sapi Betina" },
  { nomor: 3, nama: "آل عمران", namaLatin: "Ali 'Imran", slug: "ali-imran", jumlahAyat: 200, tempatTurun: "Madinah", arti: "Keluarga Imran" },
  { nomor: 4, nama: "النساء", namaLatin: "An-Nisa'", slug: "an-nisa", jumlahAyat: 176, tempatTurun: "Madinah", arti: "Wanita" },
  { nomor: 5, nama: "المائدة", namaLatin: "Al-Ma'idah", slug: "al-maidah", jumlahAyat: 120, tempatTurun: "Madinah", arti: "Hidangan" },
  { nomor: 6, nama: "الأنعام", namaLatin: "Al-An'am", slug: "al-anam", jumlahAyat: 165, tempatTurun: "Mekah", arti: "Binatang Ternak" },
  { nomor: 7, nama: "الأعراف", namaLatin: "Al-A'raf", slug: "al-araf", jumlahAyat: 206, tempatTurun: "Mekah", arti: "Tempat Tertinggi" },
  { nomor: 8, nama: "الأنفال", namaLatin: "Al-Anfal", slug: "al-anfal", jumlahAyat: 75, tempatTurun: "Madinah", arti: "Rampasan Perang" },
  { nomor: 9, nama: "التوبة", namaLatin: "At-Taubah", slug: "at-taubah", jumlahAyat: 129, tempatTurun: "Madinah", arti: "Pengampunan" },
  { nomor: 10, nama: "يونس", namaLatin: "Yunus", slug: "yunus", jumlahAyat: 109, tempatTurun: "Mekah", arti: "Yunus" },
  { nomor: 11, nama: "هود", namaLatin: "Hud", slug: "hud", jumlahAyat: 123, tempatTurun: "Mekah", arti: "Hud" },
  { nomor: 12, nama: "يوسف", namaLatin: "Yusuf", slug: "yusuf", jumlahAyat: 111, tempatTurun: "Mekah", arti: "Yusuf" },
  { nomor: 13, nama: "الرعد", namaLatin: "Ar-Ra'd", slug: "ar-rad", jumlahAyat: 43, tempatTurun: "Mekah", arti: "Guruh" },
  { nomor: 14, nama: "ابراهيم", namaLatin: "Ibrahim", slug: "ibrahim", jumlahAyat: 52, tempatTurun: "Mekah", arti: "Ibrahim" },
  { nomor: 15, nama: "الحجر", namaLatin: "Al-Hijr", slug: "al-hijr", jumlahAyat: 99, tempatTurun: "Mekah", arti: "Hijr" },
  { nomor: 16, nama: "النحل", namaLatin: "An-Nahl", slug: "an-nahl", jumlahAyat: 128, tempatTurun: "Mekah", arti: "Lebah" },
  { nomor: 17, nama: "الإسراء", namaLatin: "Al-Isra'", slug: "al-isra", jumlahAyat: 111, tempatTurun: "Mekah", arti: "Perjalanan Malam" },
  { nomor: 18, nama: "الكهف", namaLatin: "Al-Kahf", slug: "al-kahf", jumlahAyat: 110, tempatTurun: "Mekah", arti: "Gua" },
  { nomor: 19, nama: "مريم", namaLatin: "Maryam", slug: "maryam", jumlahAyat: 98, tempatTurun: "Mekah", arti: "Maryam" },
  { nomor: 20, nama: "طه", namaLatin: "Taha", slug: "taha", jumlahAyat: 135, tempatTurun: "Mekah", arti: "Taha" },
  { nomor: 21, nama: "الأنبياء", namaLatin: "Al-Anbiya'", slug: "al-anbiya", jumlahAyat: 112, tempatTurun: "Mekah", arti: "Para Nabi" },
  { nomor: 22, nama: "الحج", namaLatin: "Al-Hajj", slug: "al-hajj", jumlahAyat: 78, tempatTurun: "Madinah", arti: "Haji" },
  { nomor: 23, nama: "المؤمنون", namaLatin: "Al-Mu'minun", slug: "al-muminun", jumlahAyat: 118, tempatTurun: "Mekah", arti: "Orang-orang Mukmin" },
  { nomor: 24, nama: "النور", namaLatin: "An-Nur", slug: "an-nur", jumlahAyat: 64, tempatTurun: "Madinah", arti: "Cahaya" },
  { nomor: 25, nama: "الفرقان", namaLatin: "Al-Furqan", slug: "al-furqan", jumlahAyat: 77, tempatTurun: "Mekah", arti: "Pembeda" },
  { nomor: 26, nama: "الشعراء", namaLatin: "Asy-Syu'ara'", slug: "asy-syuara", jumlahAyat: 227, tempatTurun: "Mekah", arti: "Para Penyair" },
  { nomor: 27, nama: "النمل", namaLatin: "An-Naml", slug: "an-naml", jumlahAyat: 93, tempatTurun: "Mekah", arti: "Semut" },
  { nomor: 28, nama: "القصص", namaLatin: "Al-Qasas", slug: "al-qasas", jumlahAyat: 88, tempatTurun: "Mekah", arti: "Kisah-kisah" },
  { nomor: 29, nama: "العنكبوت", namaLatin: "Al-Ankabut", slug: "al-ankabut", jumlahAyat: 69, tempatTurun: "Mekah", arti: "Laba-laba" },
  { nomor: 30, nama: "الروم", namaLatin: "Ar-Rum", slug: "ar-rum", jumlahAyat: 60, tempatTurun: "Mekah", arti: "Bangsa Romawi" },
  { nomor: 31, nama: "لقمان", namaLatin: "Luqman", slug: "luqman", jumlahAyat: 34, tempatTurun: "Mekah", arti: "Luqman" },
  { nomor: 32, nama: "السجدة", namaLatin: "As-Sajdah", slug: "as-sajdah", jumlahAyat: 30, tempatTurun: "Mekah", arti: "Sajdah" },
  { nomor: 33, nama: "الأحزاب", namaLatin: "Al-Ahzab", slug: "al-ahzab", jumlahAyat: 73, tempatTurun: "Madinah", arti: "Golongan yang Bersekutu" },
  { nomor: 34, nama: "سبأ", namaLatin: "Saba'", slug: "saba", jumlahAyat: 54, tempatTurun: "Mekah", arti: "Kaum Saba'" },
  { nomor: 35, nama: "فاطر", namaLatin: "Fatir", slug: "fatir", jumlahAyat: 45, tempatTurun: "Mekah", arti: "Pencipta" },
  { nomor: 36, nama: "يس", namaLatin: "Ya Sin", slug: "yasin", jumlahAyat: 83, tempatTurun: "Mekah", arti: "Ya Sin" },
  { nomor: 37, nama: "الصافات", namaLatin: "As-Saffat", slug: "as-saffat", jumlahAyat: 182, tempatTurun: "Mekah", arti: "Barisan-barisan" },
  { nomor: 38, nama: "ص", namaLatin: "Sad", slug: "sad", jumlahAyat: 88, tempatTurun: "Mekah", arti: "Sad" },
  { nomor: 39, nama: "الزمر", namaLatin: "Az-Zumar", slug: "az-zumar", jumlahAyat: 75, tempatTurun: "Mekah", arti: "Rombongan-rombongan" },
  { nomor: 40, nama: "غافر", namaLatin: "Ghafir", slug: "ghafir", jumlahAyat: 85, tempatTurun: "Mekah", arti: "Yang Mengampuni" },
  { nomor: 41, nama: "فصلت", namaLatin: "Fussilat", slug: "fussilat", jumlahAyat: 54, tempatTurun: "Mekah", arti: "Yang Dijelaskan" },
  { nomor: 42, nama: "الشورى", namaLatin: "Asy-Syura", slug: "asy-syura", jumlahAyat: 53, tempatTurun: "Mekah", arti: "Musyawarah" },
  { nomor: 43, nama: "الزخرف", namaLatin: "Az-Zukhruf", slug: "az-zukhruf", jumlahAyat: 89, tempatTurun: "Mekah", arti: "Perhiasan" },
  { nomor: 44, nama: "الدخان", namaLatin: "Ad-Dukhan", slug: "ad-dukhan", jumlahAyat: 59, tempatTurun: "Mekah", arti: "Kabut" },
  { nomor: 45, nama: "الجاثية", namaLatin: "Al-Jasiyah", slug: "al-jasiyah", jumlahAyat: 37, tempatTurun: "Mekah", arti: "Yang Berlutut" },
  { nomor: 46, nama: "الأحقاف", namaLatin: "Al-Ahqaf", slug: "al-ahqaf", jumlahAyat: 35, tempatTurun: "Mekah", arti: "Bukit-bukit Pasir" },
  { nomor: 47, nama: "محمد", namaLatin: "Muhammad", slug: "muhammad", jumlahAyat: 38, tempatTurun: "Madinah", arti: "Muhammad" },
  { nomor: 48, nama: "الفتح", namaLatin: "Al-Fath", slug: "al-fath", jumlahAyat: 29, tempatTurun: "Madinah", arti: "Kemenangan" },
  { nomor: 49, nama: "الحجرات", namaLatin: "Al-Hujurat", slug: "al-hujurat", jumlahAyat: 18, tempatTurun: "Madinah", arti: "Kamar-kamar" },
  { nomor: 50, nama: "ق", namaLatin: "Qaf", slug: "qaf", jumlahAyat: 45, tempatTurun: "Mekah", arti: "Qaf" },
  { nomor: 51, nama: "الذاريات", namaLatin: "Az-Zariyat", slug: "az-zariyat", jumlahAyat: 60, tempatTurun: "Mekah", arti: "Angin yang Menerbangkan" },
  { nomor: 52, nama: "الطور", namaLatin: "At-Tur", slug: "at-tur", jumlahAyat: 49, tempatTurun: "Mekah", arti: "Bukit" },
  { nomor: 53, nama: "النجم", namaLatin: "An-Najm", slug: "an-najm", jumlahAyat: 62, tempatTurun: "Mekah", arti: "Bintang" },
  { nomor: 54, nama: "القمر", namaLatin: "Al-Qamar", slug: "al-qamar", jumlahAyat: 55, tempatTurun: "Mekah", arti: "Bulan" },
  { nomor: 55, nama: "الرحمن", namaLatin: "Ar-Rahman", slug: "ar-rahman", jumlahAyat: 78, tempatTurun: "Madinah", arti: "Yang Maha Pemurah" },
  { nomor: 56, nama: "الواقعة", namaLatin: "Al-Waqi'ah", slug: "al-waqiah", jumlahAyat: 96, tempatTurun: "Mekah", arti: "Hari Kiamat" },
  { nomor: 57, nama: "الحديد", namaLatin: "Al-Hadid", slug: "al-hadid", jumlahAyat: 29, tempatTurun: "Madinah", arti: "Besi" },
  { nomor: 58, nama: "المجادلة", namaLatin: "Al-Mujadilah", slug: "al-mujadilah", jumlahAyat: 22, tempatTurun: "Madinah", arti: "Wanita yang Menggugat" },
  { nomor: 59, nama: "الحشر", namaLatin: "Al-Hasyr", slug: "al-hasyr", jumlahAyat: 24, tempatTurun: "Madinah", arti: "Pengusiran" },
  { nomor: 60, nama: "الممتحنة", namaLatin: "Al-Mumtahanah", slug: "al-mumtahanah", jumlahAyat: 13, tempatTurun: "Madinah", arti: "Wanita yang Diuji" },
  { nomor: 61, nama: "الصف", namaLatin: "As-Saff", slug: "as-saff", jumlahAyat: 14, tempatTurun: "Madinah", arti: "Barisan" },
  { nomor: 62, nama: "الجمعة", namaLatin: "Al-Jumu'ah", slug: "al-jumuah", jumlahAyat: 11, tempatTurun: "Madinah", arti: "Jumat" },
  { nomor: 63, nama: "المنافقون", namaLatin: "Al-Munafiqun", slug: "al-munafiqun", jumlahAyat: 11, tempatTurun: "Madinah", arti: "Orang-orang Munafik" },
  { nomor: 64, nama: "التغابن", namaLatin: "At-Tagabun", slug: "at-tagabun", jumlahAyat: 18, tempatTurun: "Madinah", arti: "Hari Dinampakkan Kesalahan" },
  { nomor: 65, nama: "الطلاق", namaLatin: "At-Talaq", slug: "at-talaq", jumlahAyat: 12, tempatTurun: "Madinah", arti: "Talak" },
  { nomor: 66, nama: "التحريم", namaLatin: "At-Tahrim", slug: "at-tahrim", jumlahAyat: 12, tempatTurun: "Madinah", arti: "Mengharamkan" },
  { nomor: 67, nama: "الملك", namaLatin: "Al-Mulk", slug: "al-mulk", jumlahAyat: 30, tempatTurun: "Mekah", arti: "Kerajaan" },
  { nomor: 68, nama: "القلم", namaLatin: "Al-Qalam", slug: "al-qalam", jumlahAyat: 52, tempatTurun: "Mekah", arti: "Pena" },
  { nomor: 69, nama: "الحاقة", namaLatin: "Al-Haqqah", slug: "al-haqqah", jumlahAyat: 52, tempatTurun: "Mekah", arti: "Hari Kiamat" },
  { nomor: 70, nama: "المعارج", namaLatin: "Al-Ma'arij", slug: "al-maarij", jumlahAyat: 44, tempatTurun: "Mekah", arti: "Tempat Naik" },
  { nomor: 71, nama: "نوح", namaLatin: "Nuh", slug: "nuh", jumlahAyat: 28, tempatTurun: "Mekah", arti: "Nuh" },
  { nomor: 72, nama: "الجن", namaLatin: "Al-Jinn", slug: "al-jinn", jumlahAyat: 28, tempatTurun: "Mekah", arti: "Jin" },
  { nomor: 73, nama: "المزمل", namaLatin: "Al-Muzzammil", slug: "al-muzzammil", jumlahAyat: 20, tempatTurun: "Mekah", arti: "Orang yang Berselimut" },
  { nomor: 74, nama: "المدثر", namaLatin: "Al-Muddassir", slug: "al-muddassir", jumlahAyat: 56, tempatTurun: "Mekah", arti: "Orang yang Berkemul" },
  { nomor: 75, nama: "القيامة", namaLatin: "Al-Qiyamah", slug: "al-qiyamah", jumlahAyat: 40, tempatTurun: "Mekah", arti: "Kiamat" },
  { nomor: 76, nama: "الانسان", namaLatin: "Al-Insan", slug: "al-insan", jumlahAyat: 31, tempatTurun: "Madinah", arti: "Manusia" },
  { nomor: 77, nama: "المرسلات", namaLatin: "Al-Mursalat", slug: "al-mursalat", jumlahAyat: 50, tempatTurun: "Mekah", arti: "Malaikat yang Diutus" },
  { nomor: 78, nama: "النبأ", namaLatin: "An-Naba'", slug: "an-naba", jumlahAyat: 40, tempatTurun: "Mekah", arti: "Berita Besar" },
  { nomor: 79, nama: "النازعات", namaLatin: "An-Nazi'at", slug: "an-naziat", jumlahAyat: 46, tempatTurun: "Mekah", arti: "Malaikat yang Mencabut" },
  { nomor: 80, nama: "عبس", namaLatin: "'Abasa", slug: "abasa", jumlahAyat: 42, tempatTurun: "Mekah", arti: "Ia Bermuka Masam" },
  { nomor: 81, nama: "التكوير", namaLatin: "At-Takwir", slug: "at-takwir", jumlahAyat: 29, tempatTurun: "Mekah", arti: "Menggulung" },
  { nomor: 82, nama: "الإنفطار", namaLatin: "Al-Infitar", slug: "al-infitar", jumlahAyat: 19, tempatTurun: "Mekah", arti: "Terbelah" },
  { nomor: 83, nama: "المطففين", namaLatin: "Al-Mutaffifin", slug: "al-mutaffifin", jumlahAyat: 36, tempatTurun: "Mekah", arti: "Orang-orang yang Curang" },
  { nomor: 84, nama: "الإنشقاق", namaLatin: "Al-Insyaqaq", slug: "al-insyaqaq", jumlahAyat: 25, tempatTurun: "Mekah", arti: "Terbelah" },
  { nomor: 85, nama: "البروج", namaLatin: "Al-Buruj", slug: "al-buruj", jumlahAyat: 22, tempatTurun: "Mekah", arti: "Gugusan Bintang" },
  { nomor: 86, nama: "الطارق", namaLatin: "At-Tariq", slug: "at-tariq", jumlahAyat: 17, tempatTurun: "Mekah", arti: "Yang Datang di Malam Hari" },
  { nomor: 87, nama: "الأعلى", namaLatin: "Al-A'la", slug: "al-ala", jumlahAyat: 19, tempatTurun: "Mekah", arti: "Yang Paling Tinggi" },
  { nomor: 88, nama: "الغاشية", namaLatin: "Al-Ghasyiyah", slug: "al-ghasyiyah", jumlahAyat: 26, tempatTurun: "Mekah", arti: "Hari Pembalasan" },
  { nomor: 89, nama: "الفجر", namaLatin: "Al-Fajr", slug: "al-fajr", jumlahAyat: 30, tempatTurun: "Mekah", arti: "Fajar" },
  { nomor: 90, nama: "البلد", namaLatin: "Al-Balad", slug: "al-balad", jumlahAyat: 20, tempatTurun: "Mekah", arti: "Negeri" },
  { nomor: 91, nama: "الشمس", namaLatin: "Asy-Syams", slug: "asy-syams", jumlahAyat: 15, tempatTurun: "Mekah", arti: "Matahari" },
  { nomor: 92, nama: "الليل", namaLatin: "Al-Lail", slug: "al-lail", jumlahAyat: 21, tempatTurun: "Mekah", arti: "Malam" },
  { nomor: 93, nama: "الضحى", namaLatin: "Ad-Duha", slug: "ad-duha", jumlahAyat: 11, tempatTurun: "Mekah", arti: "Waktu Matahari Sepenggalahan Naik" },
  { nomor: 94, nama: "الشرح", namaLatin: "Asy-Syarh", slug: "asy-syarh", jumlahAyat: 8, tempatTurun: "Mekah", arti: "Melapangkan" },
  { nomor: 95, nama: "التين", namaLatin: "At-Tin", slug: "at-tin", jumlahAyat: 8, tempatTurun: "Mekah", arti: "Buah Tin" },
  { nomor: 96, nama: "العلق", namaLatin: "Al-'Alaq", slug: "al-alaq", jumlahAyat: 19, tempatTurun: "Mekah", arti: "Segumpal Darah" },
  { nomor: 97, nama: "القدر", namaLatin: "Al-Qadr", slug: "al-qadr", jumlahAyat: 5, tempatTurun: "Mekah", arti: "Kemuliaan" },
  { nomor: 98, nama: "البينة", namaLatin: "Al-Bayyinah", slug: "al-bayyinah", jumlahAyat: 8, tempatTurun: "Madinah", arti: "Pembuktian" },
  { nomor: 99, nama: "الزلزلة", namaLatin: "Az-Zalzalah", slug: "az-zalzalah", jumlahAyat: 8, tempatTurun: "Madinah", arti: "Kegoncangan" },
  { nomor: 100, nama: "العاديات", namaLatin: "Al-'Adiyat", slug: "al-adiyat", jumlahAyat: 11, tempatTurun: "Mekah", arti: "Kuda Perang" },
  { nomor: 101, nama: "القارعة", namaLatin: "Al-Qari'ah", slug: "al-qariah", jumlahAyat: 11, tempatTurun: "Mekah", arti: "Hari Kiamat" },
  { nomor: 102, nama: "التكاثر", namaLatin: "At-Takasur", slug: "at-takasur", jumlahAyat: 8, tempatTurun: "Mekah", arti: "Bermegah-megahan" },
  { nomor: 103, nama: "العصر", namaLatin: "Al-'Asr", slug: "al-asr", jumlahAyat: 3, tempatTurun: "Mekah", arti: "Masa" },
  { nomor: 104, nama: "الهمزة", namaLatin: "Al-Humazah", slug: "al-humazah", jumlahAyat: 9, tempatTurun: "Mekah", arti: "Pengumpat" },
  { nomor: 105, nama: "الفيل", namaLatin: "Al-Fil", slug: "al-fil", jumlahAyat: 5, tempatTurun: "Mekah", arti: "Gajah" },
  { nomor: 106, nama: "قريش", namaLatin: "Quraisy", slug: "quraisy", jumlahAyat: 4, tempatTurun: "Mekah", arti: "Suku Quraisy" },
  { nomor: 107, nama: "الماعون", namaLatin: "Al-Ma'un", slug: "al-maun", jumlahAyat: 7, tempatTurun: "Mekah", arti: "Barang-barang yang Berguna" },
  { nomor: 108, nama: "الكوثر", namaLatin: "Al-Kautsar", slug: "al-kautsar", jumlahAyat: 3, tempatTurun: "Mekah", arti: "Nikmat yang Berlimpah" },
  { nomor: 109, nama: "الكافرون", namaLatin: "Al-Kafirun", slug: "al-kafirun", jumlahAyat: 6, tempatTurun: "Mekah", arti: "Orang-orang Kafir" },
  { nomor: 110, nama: "النصر", namaLatin: "An-Nasr", slug: "an-nasr", jumlahAyat: 3, tempatTurun: "Madinah", arti: "Pertolongan" },
  { nomor: 111, nama: "اللهب", namaLatin: "Al-Lahab", slug: "al-lahab", jumlahAyat: 5, tempatTurun: "Mekah", arti: "Gejolak Api" },
  { nomor: 112, nama: "الإخلاص", namaLatin: "Al-Ikhlas", slug: "al-ikhlas", jumlahAyat: 4, tempatTurun: "Mekah", arti: "Ikhlas" },
  { nomor: 113, nama: "الفلق", namaLatin: "Al-Falaq", slug: "al-falaq", jumlahAyat: 5, tempatTurun: "Mekah", arti: "Waktu Subuh" },
  { nomor: 114, nama: "الناس", namaLatin: "An-Nas", slug: "an-nas", jumlahAyat: 6, tempatTurun: "Mekah", arti: "Manusia" }
];